services:

  backend:

    build: ./Backend
    container_name: backend

    ports:
    - "8082:3000"

    depends_on:
    - mysql

    networks:
      - my-network

  mysql:

    image: mysql:8
    container_name: my-sql

    environment:
      - MYSQL_ROOT_PASSWORD=Shruti@23

    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks: 
    - my-network

networks:
  my-network:
  